// 自动生成的代码。请勿编辑。
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
. . . . . f f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
..............fffcc.............
..............fcbddcc...........
...............fbbddcc..........
...............fcbbccf..........
..ccc.........ffccccccfffff.....
..cbbcc....fffcbbbbcbbbbbbbff...
...cbbdc.ffcccbbbbcbcbbbbbbbbf..
...fbbdcfcccccbbbcbcbbffbbbbbbff
....fbbffcccccbbbbbcb1ff11bbbcbf
....fcbbcccccccbbbbb11111111bbbf
....fcccccccccccbbbb11cc33111bf.
...fcbbffbdbcccccbbb111c13cccf..
...fbbf..ccddddcfbbbc111c31cf...
..fbbf.....ccdccbbdbf111cccf....
..fff........ccbbdcfcccc........
..............fffff.............
`, img`
..............fffcc.............
..............fbbddc............
...............fbbddc...........
ccc............fcbbccf..........
cbbcc.........ffccccccffffff....
.cbbdc.....fffcbbbbbbbbbbbbbff..
.fbbddc..ffcccbbbbcbcbbbbbbbbbff
..fbbdfffcccccbbbcbcbbffbbbbbcbf
..fcbbbcccccccbbbcbcb1ff1111bbbf
..fccbcccccccccbbbbbb11111111bf.
.fcbbfffccccccccbbbb11cc33cccf..
.fbbf...cbdbcccccbbb111c131cf...
fbbf.....ccdddddfbbbc111c33f....
fff........ccddfbbdbf1111ff.....
.............cfbbdbfccccc.......
..............fffff.............
`, img`
..............fffc..............
..............fbddcc............
..ccc.........ffbddbc...........
..cbbc.........fcbbccf..........
...cbdc.......ffccccccfffffff...
...fbdc....fffcbbbbbbbbbbbbbcff.
....fbdc.ffcccbbbbbbcbbbbbbbbbcf
....fcdffcccccbbbcbcbbbffbbbbcbf
....fcbbccccccbbbcbcbbbff1111bbf
...fcbbccccccccbbbcbb11111111bf.
...fbbfffcccccccbbbb11bc33cccf..
..fbbf..cbdbcccccbbb111c131cf...
..fff....cbdddddccbbc111c33f....
..........ccbddccbbdf1111ff.....
............ccfbbbdfccccc.......
..............fffff.............
`, img`
..............fffcc.............
..............fbbddc............
...............fbbddc...........
ccc............fcbbccf..........
cbbcc.........ffccccccffffff....
.cbbdc.....fffcbbbbbbbbbbbbbff..
.fbbddc..ffcccbbbbcbcbbbbbbbbbff
..fbbdfffcccccbbbcbcbbffbbbbbcbf
..fcbbbcccccccbbbcbcb1ff1111bbbf
..fccbcccccccccbbbbbb11111111bf.
.fcbbfffccccccccbbbb11cc33cccf..
.fbbf...cbdbcccccbbb111c131cf...
fbbf.....ccdddddfbbbc111c33f....
fff........ccddfbbdbf1111ff.....
.............cfbbdbfccccc.......
..............fffff.............
`];
        }
        return null;
    })

}
// 自动生成的代码。请勿编辑。
